# Persian medical QA — open medical LLMs

Asks the same 2 Persian medical questions to every size of:
Apollo2, Apollo-MoE, MedGemma, BioMistral-7B, BiMediX / BiMediX2, Meditron, OpenBioLLM.

Nothing is downloaded: models are called through the Hugging Face router's
OpenAI-compatible API (`https://router.huggingface.co/v1`) as `<repo>:<PROVIDER>`.
Needs `HF_TOKEN` in the environment with `PROVIDER` enabled at
huggingface.co/settings/inference-providers. Models the provider doesn't serve come back
as an error row.

## HF token

In [16]:
import os
from getpass import getpass

if not os.environ.get("HF_TOKEN"):
    os.environ["HF_TOKEN"] = getpass("HF_TOKEN: ")

HF_TOKEN:  ········

## Config

In [17]:
QUESTIONS = [
    (
        "من ۳۵ ساله هستم و سه روز است که تب، سرفه خشک و درد عضلانی دارم. "
        "چه بیماری‌هایی ممکن است عامل آن باشند و چه زمانی باید به پزشک مراجعه کنم؟"
    ),
    (
        "عوارض جانبی شایع داروی متفورمین چیست و "
        "آیا مصرف آن برای بیماران مبتلا به نارسایی کلیه مناسب است؟"
    ),
]

# (family, repo_id, size in B params)
MODELS = [
    # Apollo2
    ("Apollo2", "FreedomIntelligence/Apollo2-0.5B", 0.5),
    ("Apollo2", "FreedomIntelligence/Apollo2-1.5B", 1.5),
    ("Apollo2", "FreedomIntelligence/Apollo2-2B", 2),
    ("Apollo2", "FreedomIntelligence/Apollo2-3.8B", 3.8),
    ("Apollo2", "FreedomIntelligence/Apollo2-7B", 7),
    ("Apollo2", "FreedomIntelligence/Apollo2-9B", 9),
    # Apollo-MoE
    ("Apollo-MoE", "FreedomIntelligence/Apollo-MoE-0.5B", 0.5),
    ("Apollo-MoE", "FreedomIntelligence/Apollo-MoE-1.5B", 1.5),
    ("Apollo-MoE", "FreedomIntelligence/Apollo-MoE-7B", 7),
    # MedGemma
    ("MedGemma", "google/medgemma-4b-it", 4),
    ("MedGemma", "google/medgemma-4b-pt", 4),
    ("MedGemma", "google/medgemma-27b-text-it", 27),
    ("MedGemma", "google/medgemma-27b-it", 27),
    # BioMistral
    ("BioMistral", "BioMistral/BioMistral-7B", 7),
    ("BioMistral", "BioMistral/BioMistral-7B-DARE", 7),
    ("BioMistral", "BioMistral/BioMistral-7B-TIES", 7),
    ("BioMistral", "BioMistral/BioMistral-7B-SLERP", 7),
    # BiMediX / BiMediX2
    ("BiMediX", "BiMediX/BiMediX-Bi", 47),
    ("BiMediX", "BiMediX/BiMediX-Eng", 47),
    ("BiMediX", "BiMediX/BiMediX-Ara", 47),
    ("BiMediX2", "MBZUAI/BiMediX2-8B-hf", 8),
    # Meditron
    ("Meditron", "epfl-llm/meditron-7b", 7),
    ("Meditron", "epfl-llm/meditron-70b", 70),
    ("Meditron3", "OpenMeditron/Meditron3-Gemma2-2B", 2),
    ("Meditron3", "OpenMeditron/Meditron3-Qwen2.5-7B", 7),
    ("Meditron3", "OpenMeditron/Meditron3-8B", 8),
    ("Meditron3", "OpenMeditron/Meditron3-Gemma2-9B", 9),
    ("Meditron3", "OpenMeditron/Meditron3-70B", 70),
    # OpenBioLLM
    ("OpenBioLLM", "aaditya/Llama3-OpenBioLLM-8B", 8),
    ("OpenBioLLM", "aaditya/Llama3-OpenBioLLM-70B", 70),
]

MAX_NEW_TOKENS = 512
PROVIDER = "featherless-ai"

## Runner

In [18]:
import os
import time

from openai import OpenAI

client = OpenAI(base_url="https://router.huggingface.co/v1", api_key=os.environ["HF_TOKEN"])


def ask(repo, question):
    completion = client.chat.completions.create(
        model=f"{repo}:{PROVIDER}",
        messages=[{"role": "user", "content": question}],
        max_tokens=MAX_NEW_TOKENS,
        temperature=0,
    )
    return completion.choices[0].message.content.strip()

In [19]:
results = []
for family, repo, size_b in MODELS:
    print(f"=== {repo} ===")
    for qi, q in enumerate(QUESTIONS, 1):
        row = {"family": family, "model": repo, "size_b": size_b, "q": qi}
        t = time.time()
        try:
            row |= {"answer": ask(repo, q), "error": None}
        except Exception as e:
            row |= {"answer": None, "error": repr(e)}
        row["secs"] = round(time.time() - t, 1)
        results.append(row)
        print(f"--- Q{qi} ({row['secs']}s)\n{row['answer'] or row['error']}\n")

=== FreedomIntelligence/Apollo2-0.5B ===
--- Q1 (1.2s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'FreedomIntelligence/Apollo2-0.5B\' is not a chat model.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

--- Q2 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'FreedomIntelligence/Apollo2-0.5B\' is not a chat model.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

=== FreedomIntelligence/Apollo2-1.5B ===
--- Q1 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'FreedomIntelligence/Apollo2-1.5B\' is not a chat model.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

--- Q2 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'FreedomIntelligence/Apollo2-1.5B\' is not a chat model.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

=== FreedomIntelligence/Apollo2-2B ===
--- Q1 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'FreedomIntelligence/Apollo2-2B\' is not a chat model.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

--- Q2 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'FreedomIntelligence/Apollo2-2B\' is not a chat model.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

=== FreedomIntelligence/Apollo2-3.8B ===
--- Q1 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'FreedomIntelligence/Apollo2-3.8B\' is not a chat model.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

--- Q2 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'FreedomIntelligence/Apollo2-3.8B\' is not a chat model.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

=== FreedomIntelligence/Apollo2-7B ===
--- Q1 (0.7s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'FreedomIntelligence/Apollo2-7B\' is not a chat model.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

--- Q2 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'FreedomIntelligence/Apollo2-7B\' is not a chat model.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

=== FreedomIntelligence/Apollo2-9B ===
--- Q1 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'FreedomIntelligence/Apollo2-9B\' is not a chat model.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

--- Q2 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'FreedomIntelligence/Apollo2-9B\' is not a chat model.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

=== FreedomIntelligence/Apollo-MoE-0.5B ===
--- Q1 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'FreedomIntelligence/Apollo-MoE-0.5B\' is not a chat model.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

--- Q2 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'FreedomIntelligence/Apollo-MoE-0.5B\' is not a chat model.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

=== FreedomIntelligence/Apollo-MoE-1.5B ===
--- Q1 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'FreedomIntelligence/Apollo-MoE-1.5B\' is not a chat model.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

--- Q2 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'FreedomIntelligence/Apollo-MoE-1.5B\' is not a chat model.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

=== FreedomIntelligence/Apollo-MoE-7B ===
--- Q1 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'FreedomIntelligence/Apollo-MoE-7B\' is not a chat model.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

--- Q2 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'FreedomIntelligence/Apollo-MoE-7B\' is not a chat model.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

=== google/medgemma-4b-it ===
--- Q1 (0.7s)
APIStatusError('Error code: 410 - {\'error\': {\'message\': "The requested model \'google/medgemma-4b-it\' is deprecated and no longer supported by provider \'featherless-ai\'.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_no_longer_supported\'}}')

--- Q2 (0.3s)
APIStatusError('Error code: 410 - {\'error\': {\'message\': "The requested model \'google/medgemma-4b-it\' is deprecated and no longer supported by provider \'featherless-ai\'.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_no_longer_supported\'}}')

=== google/medgemma-4b-pt ===
--- Q1 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'google/medgemma-4b-pt\' is not supported by provider \'featherless-ai\'.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

--- Q2 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'google/medgemma-4b-pt\' is not supported by provider \'featherless-ai\'.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

=== google/medgemma-27b-text-it ===
--- Q1 (12.6s)
با توجه به علائمی که ذکر کردید (تب، سرفه خشک و درد عضلانی)، چندین بیماری ممکن است عامل آن باشند. شایع‌ترین آن‌ها عبارتند از:

1.  **آنفولانزا (Flu):** این بیماری ویروسی بسیار شایع است و علائم آن معمولاً ناگهانی شروع می‌شوند و شامل تب بالا، لرز، سرفه خشک، گلودرد، درد عضلانی و خستگی شدید است.
2.  **سرماخوردگی (Common Cold):** علائم سرماخوردگی معمولاً خفیف‌تر از آنفولانزا هستند و به تدریج شروع می‌شوند. ممکن است شامل آبریزش بینی، گرفتگی بینی، گلودرد، سرفه و گاهی تب خفیف باشد. درد عضلانی در سرماخوردگی کمتر شایع است.
3.  **کووید-۱۹ (COVID-19):** این بیماری ویروسی نیز علائم مشابهی با آنفولانزا و سرماخوردگی دارد، از جمله تب، سرفه خشک، خستگی، درد عضلانی، سردرد و از دست دادن حس بویایی یا چشایی.
4.  **سایر عفونت‌های ویروسی:** ویروس‌های دیگری مانند ویروس‌های تنفسی سینسیشال (RSV) یا آدنوویروس نیز می‌توانند علائم مشابهی ایجاد کنند.
5.  **عفونت‌های باکتریایی:** اگرچه کمتر شایع است، اما برخی عفونت‌های باکتریایی مانند ذات‌الریه یا برونشیت نیز می‌توانند با تب، سرفه و درد عضلانی همراه باشند.

**چه زمانی باید به پزشک مراجعه کنید؟**

در حالی که بسیاری از موارد آنفولانزا و سرماخوردگی به خودی خود بهبود می‌یابند، در شرایط زیر حتماً باید به پزشک مراجعه کنید:

*   **تب بالا و طولانی‌مدت:** اگر تب شما بالاتر از ۳۹ درجه سانتی‌گراد است یا بیش از ۳-۴ روز طول کشیده است.
*   **تنگی نفس یا مشکل در تنفس:** این علامت می‌تواند نشانه‌ای از عفونت شدید ریوی باشد.
*   **درد قفسه سینه:** این علامت نیز نیاز به بررسی فوری دارد.
*   **بدتر شدن علائم:** اگر علائم شما

--- Q2 (16.4s)
متفورمین یکی از داروهای پرکاربرد برای درمان دیابت نوع 2 است. مانند هر دارویی، مصرف آن می‌تواند عوارض جانبی داشته باشد.

**عوارض جانبی شایع متفورمین:**

*   **مشکلات گوارشی:** این شایع‌ترین عوارض جانبی متفورمین هستند و معمولاً در ابتدای مصرف دارو یا با افزایش دوز آن رخ می‌دهند. این علائم شامل موارد زیر است:
    *   تهوع
    *   اسهال
    *   نفخ و گاز معده
    *   درد شکم
    *   بی‌اشتهایی
    *   طعم فلزی در دهان
    *   این عوارض معمولاً خفیف هستند و با ادامه مصرف دارو و سازگاری بدن بهبود می‌یابند. مصرف دارو همراه با غذا می‌تواند به کاهش این علائم کمک کند.

*   **کاهش جذب ویتامین B12:** مصرف طولانی‌مدت متفورمین می‌تواند باعث کاهش سطح ویتامین B12 در بدن شود. این امر می‌تواند منجر به کم‌خونی و مشکلات عصبی شود. پزشک ممکن است در صورت نیاز، مکمل ویتامین B12 را تجویز کند.

*   **افت قند خون (هیپوگلیسمی):** اگرچه متفورمین به تنهایی به ندرت باعث افت قند خون می‌شود، اما خطر آن در صورت مصرف همزمان با سایر داروهای دیابت، مصرف نکردن وعده‌های غذایی، یا فعالیت بدنی شدید افزایش می‌یابد. علائم افت قند خون شامل لرزش، تعریق، سرگیجه، گرسنگی و تاری دید است.

*   **سندرم اسید لاکتیک:** این یک عارضه جانبی نادر اما جدی است که در آن اسید لاکتیک در بدن جمع می‌شود. این عارضه بیشتر در افرادی که مشکلات کلیوی، کبدی، قلبی یا تنفسی دارند، یا الکل زیاد مصرف می‌کنند، رخ می‌دهد. علائم آن شامل ضعف شدید، درد عضلانی، مشکلات تنفسی، خواب‌آلودگی و درد شکم است. در صورت بروز این علائم، باید فوراً به پزشک مراجعه کرد.

**مصرف متفورمین در بیماران مبتلا به نارسایی کلیه:**

**مصرف متفورمین در بیماران مبتلا به نارسایی کلیه با

=== google/medgemma-27b-it ===
--- Q1 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'google/medgemma-27b-it\' is not supported by provider \'featherless-ai\'.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

--- Q2 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'google/medgemma-27b-it\' is not supported by provider \'featherless-ai\'.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

=== BioMistral/BioMistral-7B ===
--- Q1 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'BioMistral/BioMistral-7B\' is not supported by provider \'featherless-ai\'.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

--- Q2 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'BioMistral/BioMistral-7B\' is not supported by provider \'featherless-ai\'.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

=== BioMistral/BioMistral-7B-DARE ===
--- Q1 (18.7s)
باشاره باشه، ای باشه به بیماری هایی که باشند است بیا بیا به پزشک مراجعه کن. باشاره باشه، بیماری هایی که باشند است باشه، باشاره باشه، بیماری هایی که باشند است باشه، باشاره باشه، بیماری هایی که باشند است باشه، باشاره باشه، بیماری هایی که باشند است باشه، باشاره باشه، بیماری هایی که باشند است باشه، باشاره باشه، بیماری هایی که باشند است باشه، باشاره باشه، بیماری هایی که باشند است باشه، باشاره باشه، بیماری هایی که باشند است باشه، باشاره باشه، بیماری هایی که باشند است باشه، باشاره باشه، بیماری هایی که باشند است با

--- Q2 (4.4s)
عوارض جانبی شایع داروی متفورمین برای بیماران مبتلا به نارسایی کلیه مناسب است و این دارو برای بیماران نارسایی کلیه مناسب است. این دارو با تامین و تراز تامین و تراز تامین و تراز تامین و تراز تامین و تراز تامین و تراز تامین و تراز تامین و تراز تامین و تراز تامین و تراز تامین و تراز تامین و تراز تامین و تراز تامین و تراز تامین و تراز تامین و تراز تامین و تراز تامین و تراز تامین و تراز تامین و تراز تامین و تراز تامین و تراز تامین و تراز تامین و تراز تامین و تراز تامین و تراز تامین و تراز تامین و تراز تامین و تراز ت

=== BioMistral/BioMistral-7B-TIES ===
--- Q1 (0.3s)
APIStatusError('Error code: 410 - {\'error\': {\'message\': "The requested model \'BioMistral/BioMistral-7B-TIES\' is deprecated and no longer supported by provider \'featherless-ai\'.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_no_longer_supported\'}}')

--- Q2 (0.3s)
APIStatusError('Error code: 410 - {\'error\': {\'message\': "The requested model \'BioMistral/BioMistral-7B-TIES\' is deprecated and no longer supported by provider \'featherless-ai\'.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_no_longer_supported\'}}')

=== BioMistral/BioMistral-7B-SLERP ===
--- Q1 (6.7s)
باشند بیماری های عضلانی و باشند بیماری های سرفه خشک و باشند بیماری های تب. به پزشک مراجعه کنم باید به طبیب بیماری های عضلانی و به طبیب بیماری های سرفه خشک و به طبیب بیماری های تب باید به طبیب بیماری های عضلانی و به طبیب بیماری های سرفه خشک و به طبیب بیماری های تب باید به طبیب بیماری های عضلانی و به طبیب بیماری های سرفه خشک و به طبیب بیماری های تب باید به طبیب بیماری های عضلانی و به طبیب بیماری های سرفه خشک و به طبیب بیماری های تب باید به طبیب بیماری های عضلانی و به طبیب بیماری های سرفه خشک و به طبیب بیماری

--- Q2 (4.4s)
عوارض جانبی شایع داروی متفورمین برای بیماران مبتلا به نارسایی کلیه مناسب است. داروی متفورمین برای بیماران مبتلا به نارسایی کلیه مناسب است به این ترتیب است که این دارو برای بیماران مبتلا به نارسایی کلیه مناسب است و این دارو برای بیماران مبتلا به نارسایی کلیه مناسب است.

=== BiMediX/BiMediX-Bi ===
--- Q1 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'BiMediX/BiMediX-Bi\' is not supported by provider \'featherless-ai\'.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

--- Q2 (0.7s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'BiMediX/BiMediX-Bi\' is not supported by provider \'featherless-ai\'.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

=== BiMediX/BiMediX-Eng ===
--- Q1 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'BiMediX/BiMediX-Eng\' is not supported by provider \'featherless-ai\'.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

--- Q2 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'BiMediX/BiMediX-Eng\' is not supported by provider \'featherless-ai\'.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

=== BiMediX/BiMediX-Ara ===
--- Q1 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'BiMediX/BiMediX-Ara\' is not supported by provider \'featherless-ai\'.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

--- Q2 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'BiMediX/BiMediX-Ara\' is not supported by provider \'featherless-ai\'.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

=== MBZUAI/BiMediX2-8B-hf ===
--- Q1 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'MBZUAI/BiMediX2-8B-hf\' is not supported by provider \'featherless-ai\'.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

--- Q2 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'MBZUAI/BiMediX2-8B-hf\' is not supported by provider \'featherless-ai\'.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

=== epfl-llm/meditron-7b ===
--- Q1 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'epfl-llm/meditron-7b\' is not supported by provider \'featherless-ai\'.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

--- Q2 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'epfl-llm/meditron-7b\' is not supported by provider \'featherless-ai\'.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

=== epfl-llm/meditron-70b ===
--- Q1 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'epfl-llm/meditron-70b\' is not supported by provider \'featherless-ai\'.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

--- Q2 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'epfl-llm/meditron-70b\' is not supported by provider \'featherless-ai\'.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_supported\'}}')

=== OpenMeditron/Meditron3-Gemma2-2B ===
--- Q1 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'OpenMeditron/Meditron3-Gemma2-2B\' does not exist.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_found\'}}')

--- Q2 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'OpenMeditron/Meditron3-Gemma2-2B\' does not exist.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_found\'}}')

=== OpenMeditron/Meditron3-Qwen2.5-7B ===
--- Q1 (0.7s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'OpenMeditron/Meditron3-Qwen2.5-7B\' does not exist.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_found\'}}')

--- Q2 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'OpenMeditron/Meditron3-Qwen2.5-7B\' does not exist.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_found\'}}')

=== OpenMeditron/Meditron3-8B ===
--- Q1 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'OpenMeditron/Meditron3-8B\' does not exist.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_found\'}}')

--- Q2 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'OpenMeditron/Meditron3-8B\' does not exist.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_found\'}}')

=== OpenMeditron/Meditron3-Gemma2-9B ===
--- Q1 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'OpenMeditron/Meditron3-Gemma2-9B\' does not exist.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_found\'}}')

--- Q2 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'OpenMeditron/Meditron3-Gemma2-9B\' does not exist.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_found\'}}')

=== OpenMeditron/Meditron3-70B ===
--- Q1 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'OpenMeditron/Meditron3-70B\' does not exist.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_found\'}}')

--- Q2 (0.3s)
BadRequestError('Error code: 400 - {\'error\': {\'message\': "The requested model \'OpenMeditron/Meditron3-70B\' does not exist.", \'type\': \'invalid_request_error\', \'param\': \'model\', \'code\': \'model_not_found\'}}')

=== aaditya/Llama3-OpenBioLLM-8B ===
--- Q1 (20.9s)
There are several possible causes for your symptoms, including respiratory infections such as the common cold or influenza, as well as muscle strain. It is recommended that you consult a healthcare professional if your symptoms persist or worsen.

--- Q2 (4.4s)
What are the common side effects of Metformin and is it appropriate for patients with kidney failure to take it?

=== aaditya/Llama3-OpenBioLLM-70B ===
--- Q1 (41.6s)
JSONDecodeError('Extra data: line 1 column 1355 (char 1354)')

--- Q2 (33.5s)

## Results

In [20]:
import pandas as pd
from IPython.display import HTML, display

df = pd.DataFrame(results)
df.to_csv("persian_medical_qa_results.csv", index=False)
display(df[df.error.notna()][["model", "q", "error"]])

ok = df[df.error.isna()].pivot(index=["family", "model", "size_b"], columns="q", values="answer")
ok.columns = [f"Q{c}" for c in ok.columns]
display(HTML(f'<div dir="rtl" style="text-align:right">{ok.to_html()}</div>'))

,model,q,error
0,FreedomIntelligence/Apollo2-0.5B,1,BadRequestError('Error code: 400 - {\'error\':...
1,FreedomIntelligence/Apollo2-0.5B,2,BadRequestError('Error code: 400 - {\'error\':...
2,FreedomIntelligence/Apollo2-1.5B,1,BadRequestError('Error code: 400 - {\'error\':...
3,FreedomIntelligence/Apollo2-1.5B,2,BadRequestError('Error code: 400 - {\'error\':...
4,FreedomIntelligence/Apollo2-2B,1,BadRequestError('Error code: 400 - {\'error\':...
5,FreedomIntelligence/Apollo2-2B,2,BadRequestError('Error code: 400 - {\'error\':...
6,FreedomIntelligence/Apollo2-3.8B,1,BadRequestError('Error code: 400 - {\'error\':...
7,FreedomIntelligence/Apollo2-3.8B,2,BadRequestError('Error code: 400 - {\'error\':...
8,FreedomIntelligence/Apollo2-7B,1,BadRequestError('Error code: 400 - {\'error\':...
9,FreedomIntelligence/Apollo2-7B,2,BadRequestError('Error code: 400 - {\'error\':...
10,FreedomIntelligence/Apollo2-9B,1,BadRequestError('Error code: 400 - {\'error\':...
11,FreedomIntelligence/Apollo2-9B,2,BadRequestError('Error code: 400 - {\'error\':...
12,FreedomIntelligence/Apollo-MoE-0.5B,1,BadRequestError('Error code: 400 - {\'error\':...
13,FreedomIntelligence/Apollo-MoE-0.5B,2,BadRequestError('Error code: 400 - {\'error\':...
14,FreedomIntelligence/Apollo-MoE-1.5B,1,BadRequestError('Error code: 400 - {\'error\':...
15,FreedomIntelligence/Apollo-MoE-1.5B,2,BadRequestError('Error code: 400 - {\'error\':...
16,FreedomIntelligence/Apollo-MoE-7B,1,BadRequestError('Error code: 400 - {\'error\':...
17,FreedomIntelligence/Apollo-MoE-7B,2,BadRequestError('Error code: 400 - {\'error\':...
18,google/medgemma-4b-it,1,APIStatusError('Error code: 410 - {\'error\': ...
19,google/medgemma-4b-it,2,APIStatusError('Error code: 410 - {\'error\': ...
20,google/medgemma-4b-pt,1,BadRequestError('Error code: 400 - {\'error\':...
21,google/medgemma-4b-pt,2,BadRequestError('Error code: 400 - {\'error\':...
24,google/medgemma-27b-it,1,BadRequestError('Error code: 400 - {\'error\':...
25,google/medgemma-27b-it,2,BadRequestError('Error code: 400 - {\'error\':...
26,BioMistral/BioMistral-7B,1,BadRequestError('Error code: 400 - {\'error\':...
27,BioMistral/BioMistral-7B,2,BadRequestError('Error code: 400 - {\'error\':...
30,BioMistral/BioMistral-7B-TIES,1,APIStatusError('Error code: 410 - {\'error\': ...
31,BioMistral/BioMistral-7B-TIES,2,APIStatusError('Error code: 410 - {\'error\': ...
34,BiMediX/BiMediX-Bi,1,BadRequestError('Error code: 400 - {\'error\':...
35,BiMediX/BiMediX-Bi,2,BadRequestError('Error code: 400 - {\'error\':...
36,BiMediX/BiMediX-Eng,1,BadRequestError('Error code: 400 - {\'error\':...
37,BiMediX/BiMediX-Eng,2,BadRequestError('Error code: 400 - {\'error\':...
38,BiMediX/BiMediX-Ara,1,BadRequestError('Error code: 400 - {\'error\':...
39,BiMediX/BiMediX-Ara,2,BadRequestError('Error code: 400 - {\'error\':...
40,MBZUAI/BiMediX2-8B-hf,1,BadRequestError('Error code: 400 - {\'error\':...
41,MBZUAI/BiMediX2-8B-hf,2,BadRequestError('Error code: 400 - {\'error\':...
42,epfl-llm/meditron-7b,1,BadRequestError('Error code: 400 - {\'error\':...
43,epfl-llm/meditron-7b,2,BadRequestError('Error code: 400 - {\'error\':...
44,epfl-llm/meditron-70b,1,BadRequestError('Error code: 400 - {\'error\':...
45,epfl-llm/meditron-70b,2,BadRequestError('Error code: 400 - {\'error\':...
46,OpenMeditron/Meditron3-Gemma2-2B,1,BadRequestError('Error code: 400 - {\'error\':...
47,OpenMeditron/Meditron3-Gemma2-2B,2,BadRequestError('Error code: 400 - {\'error\':...
48,OpenMeditron/Meditron3-Qwen2.5-7B,1,BadRequestError('Error code: 400 - {\'error\':...
49,OpenMeditron/Meditron3-Qwen2.5-7B,2,BadRequestError('Error code: 400 - {\'error\':...
50,OpenMeditron/Meditron3-8B,1,BadRequestError('Error code: 400 - {\'error\':...
51,OpenMeditron/Meditron3-8B,2,BadRequestError('Error code: 400 - {\'error\':...
52,OpenMeditron/Meditron3-Gemma2-9B,1,BadRequestError('Error code: 400 - {\'error\':...
53,OpenMeditron/Meditron3-Gemma2-9B,2,BadRequestError('Error code: 400 - {\'error\':...
54,OpenMeditron/Meditron3-70B,1,BadRequestError('Error code: 400 - {\'error\':...
55,OpenMeditron/Meditron3-70B,2,BadRequestError('Error code: 400 - {\'error\':...
58,aaditya/Llama3-OpenBioLLM-70B,1,JSONDecodeError('Extra data: line 1 column 135...